configuration:
  logging:
    # level Set the log level
    level: 10
  database:
    username: postgres
    password: postgres
    host: postgres.flyte
    dbname: flyte
  storage:
    type: minio
    metadataContainer: flyte
    userDataContainer: flyte
    provider: s3
    providerConfig:
      s3:
        region: "us-east-1" #Irrelevant for local but still needed
        authType: "accesskey"
        endpoint: "http://flyte.local:30084"
        accessKey: "minio"
        secretKey: "miniostorage"
        disableSSL: "true"
        secure: "false"
  
  #inlineSecretRef: flyte-binary-inline-config-secret  
  inline:
    plugins:
      k8s:
        inject-finalizer: true
        default-env-vars:
          - FLYTE_AWS_ENDPOINT: "http://flyte.local:30084"
          - FLYTE_AWS_ACCESS_KEY_ID: "minio"
          - FLYTE_AWS_SECRET_ACCESS_KEY: "miniostorage"
    task_resources:
      defaults: 
        cpu: 1000m
        memory: 500Mi #change default requested resources and limits to fit your needs
      limits:
        cpu: 2000m
        memory: 2000Mi
    storage:
      cache:
        max_size_mbs: 100
        target_gc_percent: 100
# ingress Configure ingress for Flyte
ingress:
  create: true
  host: flyte.local
  separateGrpcIngress: true
  commonAnnotations:
    kubernetes.io/ingress.class: public
  httpAnnotations:
    nginx.ingress.kubernetes.io/app-root: /console
  grpcAnnotations:
    nginx.ingress.kubernetes.io/backend-protocol: GRPC

serviceAccount:
  create: true
