version: '3'

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ~/somelocalpath:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniostorage
      MINIO_DEFAULT_BUCKETS: flyte

    command: server /data --console-address ":9090"